### ISSUE TITLE
Connection without localhost

### ISSUE THREAD

**Issue by JamieS1211** [KaiKikuchi/SynX#2]
When starting the server if the config does not specify localhost then connection will fail and be refused.

**Comment by KaiKikuchi** [comment]
You have to specify your MySQL server info because SynX uses a MySQL database to transfer transfer data. This is intended and quite an obvious thing.

**Comment by JamieS1211** [comment]
Config on personal machine on local network with server that runs MySQL (192.168.1.67).
On startup I get this error http://pastebin.com/0yhFYhLY

`DataExchangerThrottleTime=500
Debug=false
DefaultTTL=86400000
MySQL {
    Database=SynX
    Hostname=192.168.1.67
    Password=####
    Username=root
}
NodeName=pc
Tags=[
    default
]`

When on that server (192.168.1.67) if I copy that config chaning NodeName to xeon I get the same error (this time after a long time - http://pastebin.com/UaC1eSdq). If (still on 192.168.1.67) I now change hostname to local host it seems to connect just fine (but localhost is the same as 192.167.1.67) and I still get an error when using anything other then localhost.

**Comment by KaiKikuchi** [comment]
It's still unrelated to SynX.

You are using the root mysql account, by default you can access it from localhost (127.0.0.1) only. Either remove this restriction (but you shouldn't do that for security reasons), or make a new mysql user and grant permissions to the database you want to use.

**Comment by JamieS1211** [comment]
Well this is embarrassing.... I have run MySQL for 5 years and never knew that. Head going in bucket now. Thanks
