### ISSUE TITLE
SynX not working

### ISSUE THREAD

**Issue by TheBolly** [KaiKikuchi/SynX#4]
Hello, I messaged about a week ago on Twitter about an issue. Here is what I have been experiencing..

I am currently on my test servers trying to setup SynX but have been experiencing some issues.

I first put all the plugins in that were needed for the plugin to run and followed the instructions.
My Bungeecord server ran and created the folder for me to put the information in.

However, the spigot server did not work. It gave the 'file not found exception'. I then tried to put the config in manually by copying the folder from Bungeecord. Still no luck.

Below I have supplied the logs for each server. However, when it comes to it. I shall also need this working on Sponge with our servers there.

Spigot Server log - https://pastebin.com/v0xhBZex
Bungeecord log - https://pastebin.com/BHnxWBrY

If you could help me with this issue that would be great!

I'd also be willing to speak on Discord if that could help.

Bolly.

**Comment by KaiKikuchi** [comment]
Hello, please try again with the latest versions:
- SynX: https://github.com/KaiKikuchi/KaisCommons/releases
- KaisCommons: https://github.com/KaiKikuchi/KaisCommons/releases

**Comment by TheBolly** [comment]
I have just tested with both those new versions. But still receiving the same error I'm afriad

**Comment by KaiKikuchi** [comment]
Please try with this:
https://github.com/KaiKikuchi/SynX/releases/tag/v.1.2.3

**Comment by TheBolly** [comment]
Thank you! It now works, tomorrow I will test it on the Sponge server also.
